const fs=require('fs'),path=require('path'),assert=require('assert'),H=require('../dist/hydro.js'),D=require('../dist/decision.js');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const context=H.prepare(read('dist/hydro_context.json')),bundle=read('dist/hydro_models.json'),validation=read('dist/hydro_validation.json');
let references=0,maxDistanceError=0,maxScoreError=0;
for(const t of Object.values(bundle.tasks))for(const ref of t.reference_predictions){const f=H.features(context,ref.record.latitude,ref.record.longitude),pr=H.infer(t,f);assert.equal(f.hydrolithological_domain,ref.record.hydrolithological_domain);assert.equal(f.domain_polygon_matches,ref.record.domain_polygon_matches);maxDistanceError=Math.max(maxDistanceError,Math.abs(f.mapped_structure_distance_km-ref.record.mapped_structure_distance_km));maxScoreError=Math.max(maxScoreError,Math.abs(pr.score-ref.score),Math.abs(pr.tree_std-ref.tree_std));assert(maxDistanceError<1e-8);assert(maxScoreError<1e-8);references++;}
for(const t of Object.values(validation.tasks))for(const e of t.evaluations){assert.equal(e.tested_n,t.n);assert.equal(e.coverage,1);for(const f of e.folds){assert(!f.skipped);assert(f.minimum_train_test_km+1e-12>=e.buffer_km);assert(f.train_n<=f.train_before);}}
const polygon={type:'Polygon',coordinates:[[[0,0],[4,0],[4,4],[0,4],[0,0]],[[1,1],[3,1],[3,3],[1,3],[1,1]]]};assert(H.covers(polygon,[0,2]));assert(H.covers(polygon,[.5,2]));assert(!H.covers(polygon,[2,2]));assert(H.covers(polygon,[1,2]));assert(!H.covers(polygon,[5,5]));
const options=[{id:'A',flow_m3_h:5,hours_day:6,tds_mg_l:5000,recovery:.5,rejection:.98,dynamic_head_m:80,pump_efficiency:.55,ro_kwh_per_m3_permeate:5,fixed_cost_brl_day:13},{id:'B',flow_m3_h:2,hours_day:6,tds_mg_l:2000,recovery:.6,rejection:.98,dynamic_head_m:50,pump_efficiency:.65,ro_kwh_per_m3_permeate:2,fixed_cost_brl_day:13},{id:'C',flow_m3_h:1.5,hours_day:6,tds_mg_l:1200,recovery:.7,rejection:.98,dynamic_head_m:40,pump_efficiency:.6,ro_kwh_per_m3_permeate:1.5,fixed_cost_brl_day:13}],c={available_kwh_day:18,energy_brl_kwh:0,concentrate_brl_m3:1.5,daily_budget_brl:80,tds_limit_mg_l:500,demand_m3_day:4};
const example=D.compare(options,c);assert.equal(example.strategies.production,'A');assert.equal(example.strategies.production_and_feed_salinity,null);assert.equal(example.strategies.conditional_treated_water,'B');
let scenarios=0,maxSaltResidual=0;
for(const energy of [0,.1,10,100])for(const recovery of [.1,.5,.9])for(const budget of [0,13,20,100]){const q=D.evaluate({...options[0],recovery},{...c,available_kwh_day:energy,daily_budget_brl:budget});assert(q.feed_m3<=30+1e-10);assert(q.energy_kwh<=energy+1e-10);if(q.budget_eligible)assert(q.cost_brl<=budget+1e-10);else assert.equal(q.feed_m3,0);assert(Math.abs(q.volume_balance_m3)<1e-10);maxSaltResidual=Math.max(maxSaltResidual,Math.abs(q.salt_balance_kg));assert(Math.abs(q.salt_balance_kg)<1e-9);scenarios++;}
assert.throws(()=>D.evaluate({...options[0],recovery:1},c),/inválido/);assert.throws(()=>D.evaluate({...options[0],flow_m3_h:NaN},c),/inválido/);assert.throws(()=>D.compare([options[0],options[0]],c),/únicos/);assert.equal(D.evaluate({...options[0],rejection:0},c).conditional_volume_m3,0);assert.equal(D.compare(options,{...c,available_kwh_day:0}).strategies.conditional_treated_water,null);
const candidates=Array.from({length:12},(_,i)=>({id:'s'+String(i).padStart(2,'0'),latitude:-7,longitude:-37+i*.02,production:{score:1-i*.02,tree_std:.1+i*.01},salinity:{score:.4,tree_std:.2}})),visits=H.selectVisits(candidates);assert.equal(visits.length,6);assert.equal(visits[0].id,'s00');for(let i=0;i<visits.length;i++)for(let j=0;j<i;j++)assert(H.distance([visits[i].latitude,visits[i].longitude],[visits[j].latitude,visits[j].longitude])>=1);
const result={passed:true,geological_python_reference_cases:references,max_structure_distance_error_km:maxDistanceError,max_score_or_tree_std_error:maxScoreError,buffered_configurations_checked:18,treatment_conservation_scenarios:scenarios,max_salt_residual_kg:maxSaltResidual,checks:['derived domain and polygon-hole boundary handling','Python-to-JavaScript geological RF predictions','buffer distances and full held-out coverage','shared energy/budget and water/salt balance','strategy difference in hypothetical examples','missing/invalid input rejection','spatial visit separation'],limitations:['Software verification is not field validation','Full browser layout not tested']};fs.writeFileSync(path.join(__dirname,'qa_v2_1.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
